### PR TITLE
Added pre-commit, flake8 and venv in .gitignore.

### PR DESCRIPTION
**Pull request by himadriganguly**

### CODE REVIEW

**Comment by himadriganguly** [comment]
Also added **python typing** in **utils.py** with this **PR**.

**Comment by roclark** [comment]
Hey @himadriganguly, thanks for opening a PR! I'm a little confused here - I don't see a description for the PR, and it looks like the commits are all doing different things and overwriting some of the updates in the PR itself. Is this tied to a particular issue in the repo? I see a bulk of these changes are to the single quotes being updated to double quotes as well - I've always been partial to the single quotes in Python, and don't think it would be valuable to do a whole-sale change to double quotes for the repository as that adds a massive commit with no meaningful difference, unless I am mistaken on the purpose. Do you mind providing some more context on this PR? I'm afraid I can't accept this as-is without some changes and a description and, ideally, a link to a specific issue.

Thanks again for taking the time to work on this though, and your interest in sportsreference!

**Comment by himadriganguly** [comment]
Thanks, @roclark for the comment.

The following are the changes:-

**1.** Added Python typing in utils.py with this PR.
**2.** Fixed **E501** error in all the files using **pycodestyle**
**3.** Added pre-commit hook with **autopep8** and **flake8**
**4.** Modified **setup.py** to fix error '**classifiers**' should be a **list**, got type '**tuple**'.
**5.** Added venv folder in **.gitignore** for **virtualenv**.

**Comment by roclark** [comment]
Thanks for the explanation! I think that's a bit why I'm confused - these changes seem to be very different from one another in my opinion, and in the case of a few, like with fixing the E501 error using pycodestyle, it appears to be an issue that was brought on by one of the previous commits in this PR and not something existing in the current upstream codebase. I'm assuming part of this was cleanup from using the various auto-formatting tools? This is actually one of the main reasons I tend to shy away from auto-formatters like `autopep8` and `flake8` as I find they tend to do more harm then good in the long run. While I think it's important to follow stylistic guidelines, I find it best to present any formatting issues in non-invasive ways, such as the outputs from the Actions on GitHub and allow developers to fix them in a logical manner. Users can also run the code manually on the commits prior to pushing, but if we want to truly enforce solid Python practices, I am not certain that these auto-formatters are the best route to follow.

Again, I greatly appreciate you taking the time to make this PR! I'd be happy to accept additional feedback or updates, but I will close this PR for now as I don't believe it fully fits with the vision here.

**Pull request closed without merging**
